---
- name: meraki deployment
  hosts: localhost
  vars:
    auth_key: "{{ auth }}"
    org_name: "{{ org }}"
    net_work: "{{ net }}"

  tasks:

    - name: include variables for devices
      include_vars:
        file: devices.yaml
        name: devices

    - name: include variables for addresses
      include_vars:
        file: addresses.yaml
        name: addresses


    - name: Remove site network
      meraki_network:
        auth_key: "{{ auth_key }}"
        state: absent
        org_name: "{{ org_name }}"
        name: "{{ item.value.network_name }}"
        type:
          - switch
          - appliance
          - wireless
      register: off_network
      loop: "{{ lookup('dict', devices, wantlist=True) }}"
      when: "'device-1' in item.key"


